input_dir_folder: /home/mbugueno/TC_graphs/Data_RBased/
output_dir_folder: /home/mbugueno/

dataset: bbc

num_classes: 5

pre_trained_model: bert-base-uncased

path_metrics: /home/mbugueno/GRTC_GNNs/LMs/Results/

pre_file: WANDB_ 

training: 
    batch_size: 32
    max_epochs: 100
    dropout: 0.2
    max_length: 512
    lr: 0.00001
    

experiment: 
  runs: 1 
  patience: 2
  type_train: FT
  language-model: BERT
  